name: TMATE VPS
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Auto Root Setup
        run: echo "exec sudo -i" >> ~/.bashrc
      - name: Setup TMATE
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
      - name: Keep Alive
        run: |
          while true; do
            sleep 900
            echo "VPS Active"
          done
